configName: sam_l21_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAML21J18B
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;core_apps_pic32cm_mc00;crypto;cryptoauthlib;cryptoauthlib_apps;csp;csp_apps_pic32cm_mc00;csp_apps_sam_d5x_e5x;csp_apps_sam_l21;gfx;micrium_ucos3;net;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAML21_DFP\3.4.76\saml21b\atdf\ATSAML21J18B.atdf
