format_version: v1.0
type: UniqueComponent
attributes: {id: dac}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DAC_CHANNEL_1_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: DAC_CHANNEL_1_SPEED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: KeyValueSet
    attributes: {id: DAC_REFSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '310', y: '61', id: dac}
